
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class AddSite extends javax.swing.JFrame {

    /**
     * Creates new form AddSite
     */
    public AddSite() throws SQLException {
        initComponents();
        InvoiceNo();
    }
    
    public void InvoiceNo() throws SQLException{
        String query = "SELECT MAX(Site_ID)FROM site ";
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = databaseConnection.con().prepareStatement(query);
            rs = ps.executeQuery();
            if(rs.next()){
            rs.getString("MAX(Site_ID)");
            
            if(rs.getString("MAX(Site_ID)")==null){
                jTextFielda.setText("S001");
            }else{
               
                
                String id=String.valueOf(rs.getString("MAX(Site_ID)"));
             
                String id1=id.substring(0,1);
                String id2=id.substring(2,4);
               long n= Long.parseLong(id2);
                n++;
                String num1=Long.toString(n);
                jTextFielda.setText(id1+String.format("%03d",n));
            }
            }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextFielda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFielde = new javax.swing.JTextField();
        jTextFieldd = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldj = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldl = new javax.swing.JTextField();
        jTextFieldk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 590));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("New Site");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(20, 20, 130, 50);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(950, 30, 67, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1050, 90);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(690, 390, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(770, 440, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(860, 390, 80, 30);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Site details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Site ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 20, 90, 30);

        jTextFielda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldaActionPerformed(evt);
            }
        });
        jTextFielda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldaKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFielda);
        jTextFielda.setBounds(140, 20, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Site name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 67, 50);

        jTextFieldb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbActionPerformed(evt);
            }
        });
        jTextFieldb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldbKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldb);
        jTextFieldb.setBounds(140, 70, 310, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Location:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 120, 67, 30);

        jTextFieldc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcActionPerformed(evt);
            }
        });
        jTextFieldc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldcKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldc);
        jTextFieldc.setBounds(140, 120, 310, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Project Manager :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 370, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("E mail:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 217, 67, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tele No:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 180, 67, 17);

        jTextFielde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFielde);
        jTextFielde.setBounds(140, 220, 310, 30);

        jTextFieldd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddActionPerformed(evt);
            }
        });
        jTextFieldd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFielddKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldd);
        jTextFieldd.setBounds(140, 170, 310, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(310, 20, 80, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Started Date :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 270, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Status :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 420, 100, 20);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(140, 270, 310, 30);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(140, 320, 310, 30);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(140, 370, 140, 30);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Completed");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(140, 420, 90, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Not completed");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(250, 420, 110, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ending Date :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 320, 100, 30);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(50, 100, 470, 450);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Client Name :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 30, 90, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tele No:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 100, 67, 30);

        jTextFieldj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldjActionPerformed(evt);
            }
        });
        jTextFieldj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldjKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldj);
        jTextFieldj.setBounds(150, 40, 240, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("E mail:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 160, 70, 40);

        jTextFieldl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldlActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldl);
        jTextFieldl.setBounds(150, 170, 240, 30);

        jTextFieldk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldkActionPerformed(evt);
            }
        });
        jTextFieldk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldkKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldk);
        jTextFieldk.setBounds(150, 100, 240, 30);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(550, 100, 470, 230);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1050, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldaActionPerformed

    private void jTextFieldbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbActionPerformed

    private void jTextFieldcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcActionPerformed

    private void jTextFieldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldeActionPerformed

    private void jTextFieldjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldjActionPerformed

    private void jTextFieldlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldlActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
        SiteDetailsAdmin a= new SiteDetailsAdmin();
        a.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ResultSet rs=null;
        try {
            String a= jTextFielda.getText();
            String query ="SELECT  * FROM `site`  WHERE Site_ID = ? ";
            PreparedStatement ps=null;
            ps=databaseConnection.con().prepareStatement(query);
            ps.setString(1, a);
            rs=ps.executeQuery();
            if(rs.next()){
                
            jTextFieldb.setText(rs.getString("Name"));
            jTextFieldc.setText(rs.getString("Location"));
            jTextFieldd.setText(rs.getString("Telephone_no"));
            jTextFielde.setText(rs.getString("E_mail"));
             String datevalue=rs.getString("Started_date");
             String datevalue2=rs.getString("Ending_date");
           // jTextField1.setText(rs.getString("Project_Manager"));
             try {
                 java.util.Date date= new SimpleDateFormat("yyyy-MM-dd").parse(datevalue);
                 java.util.Date date2= new SimpleDateFormat("yyyy-MM-dd").parse(datevalue2);
                jDateChooser1.setDate(date);
                jDateChooser2.setDate(date2);
                } catch (ParseException ex) {
                    Logger.getLogger(AddSite.class.getName()).log(Level.SEVERE, null, ex);
                }
             
             jComboBox1.setSelectedItem(rs.getString("Project_Manager"));
            // jComboBox2.addItem(rs.getString("CID"));
           // jTextField1.setText(rs.getString("CID"));
           String c=(rs.getString("Status"));
                if(c.equals("Completed")){
                    jRadioButton1.setSelected(true);
                }else{
                    jRadioButton2.setSelected(true);
                }
            jTextFieldj.setText(rs.getString("Client_name"));
            jTextFieldk.setText(rs.getString("C_tp"));
            jTextFieldl.setText(rs.getString("C_email"));
            
            
            
               
                
            
            }
                 else{
                JOptionPane.showMessageDialog(this, "Site Not Found!");
                jTextFielda.setText("");
                }
                 } catch (SQLException ex) {
            Logger.getLogger(Sites.class.getName()).log(Level.SEVERE, null, ex);
        
            }
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                    jTextFielda.setText("");
                    jTextFieldb.setText("");
                    jTextFieldc.setText("");
                    jTextFieldd.setText("");
                    jTextFielde.setText("");
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                    jComboBox1.setSelectedItem(null);
                   // jComboBox2.setSelectedItem(null);
                  // jRadioButton1.setSelected(false);
                    //jRadioButton2.setSelected(false);
                   buttonGroup1.clearSelection();
                    jTextFieldj.setText("");
                    jTextFieldk.setText("");
                    jTextFieldl.setText("");
                   
                    
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            PreparedStatement ps=null;
            PreparedStatement ps2=null;
            ResultSet rs1=null;
            ResultSet rs2=null;
            
            String a=jTextFielda.getText();
            String b=jTextFieldb.getText();
            String c=jTextFieldc.getText();
            String d=jTextFieldd.getText();
            String e=jTextFielde.getText();
            //String f=jTextFieldf.getText();
            //String g=jTextFieldg.getText();
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                String f=sdf.format(jDateChooser1.getDate());
                String g=sdf.format(jDateChooser2.getDate());
           String h=String.valueOf(jComboBox1.getSelectedItem());
           // String i=String.valueOf(jComboBox1.getSelectedItem());
           //String i=jTextField1.getText();
           String i="";
            if(jRadioButton1.isSelected()){
                 i="Completed";
            }else{
                i="Not completed";
            }
            String j=jTextFieldj.getText();
            String k=jTextFieldk.getText();
            String l=jTextFieldl.getText();
            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || f.equals("") || g.equals("") ||  h.equals("") ||  j.equals("") || k.equals("") || l.equals("") || i.equals("")  ){
               JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
               
            } else{  
            String query_A="SELECT * FROM `site` WHERE Site_ID=? ";
            ps=databaseConnection.con().prepareStatement(query_A);
            ps.setString(1, a);
            rs1=ps.executeQuery();
            
            if(rs1.next()){
                JOptionPane.showMessageDialog(this,"Invalid SiteID");
            }
            else{  
                String query= "INSERT INTO `site`"
                        +"(`Site_ID`, `Name`, `Location`, `Telephone_no`, `E_mail`, `Started_date`, `Ending_date`, `Project_Manager`,`Client_name`, `C_tp`, `C_email`,`Status`)"
                        +"VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
                
//                String query2= "INSERT INTO `client`"
//                    +"(`Client_ID`, `Name`, `Telephone_NO`, `Email`, `SiteID`)"
//                    +"VALUES (?,?,?,?,?)";
            String Query2="UPDATE `project_manager` SET `CurrentSite`=? WHERE PM_ID=?";
             ps=databaseConnection.con().prepareStatement(Query2);
              ps.setString(1,a);
              ps.setString(2,h);
              ps.executeUpdate();
              
           
                
            ps=databaseConnection.con().prepareStatement(query);
            //ps2=databaseConnection.con().prepareStatement(query2);

       
            ps.setString(1,a);
            ps.setString(2,b);
            ps.setString(3,c);
            ps.setString(4,d);
            ps.setString(5,e);
            ps.setString(6,f);
            ps.setString(7,g);
            ps.setString(8,h);
            ps.setString(9,j);
            ps.setString(10,k);
            ps.setString(11,l);
            ps.setString(12,i);
           
            
//            ps2.setString(1,i);
//            ps2.setString(2,j);
//            ps2.setString(3,k);
//            ps2.setString(4,l);
//            ps2.setString(5,a);
            
            ps.execute();
           // ps2.execute();
            
            JOptionPane.showMessageDialog(this, "New Site has been created");
             jTextFielda.setText("");
                    jTextFieldb.setText("");
                    jTextFieldc.setText("");
                    jTextFieldd.setText("");
                    jTextFielde.setText("");
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                    jComboBox1.setSelectedItem(null);
                    //jComboBox2.setSelectedItem(null);
                    //jTextField1.setText("");
                    jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(false);
                    jTextFieldj.setText("");
                    jTextFieldk.setText("");
                    jTextFieldl.setText("");
            }
            }   
                  
            }catch (SQLException ex) {
            Logger.getLogger(Sites.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            try{
            String a=jTextFielda.getText();
            String b=jTextFieldb.getText();
            String c=jTextFieldc.getText();
            String d=jTextFieldd.getText();
            String e=jTextFielde.getText();
           // String f=jTextFieldf.getText();
           // String g=jTextFieldg.getText();
           String i="";
             if(jRadioButton1.isSelected()){
                 i="Completed";
            }else{
                i="Not completed";
            }
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
            String f=sdf.format(jDateChooser1.getDate());
            String g=sdf.format(jDateChooser2.getDate());
           String h=String.valueOf(jComboBox1.getSelectedItem());
            //String i=String.valueOf(jComboBox1.getSelectedItem());
            //String i=jTextField1.getText();
            String j=jTextFieldj.getText();
            String k=jTextFieldk.getText();
            String l=jTextFieldl.getText();
            
            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") ||  e.equals("") ||f.equals("") || g.equals("") ||  h.equals("") ||  j.equals("") || k.equals("") || l.equals("")  ){
               JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
              
            } 
            else{ 
                
                  String query= "UPDATE `site` SET  `Name`=?,`Location`=?,`Telephone_no`=?,`E_mail`=?,`Started_date`=?,`Ending_date`=?,`Project_Manager`=?,`Client_name`=?,`C_tp`=?,`C_email`=?,`Status`=?  WHERE  `Site_ID`=?";
                  PreparedStatement ps1=null;
                 
                  ps1=databaseConnection.con().prepareStatement(query);
                  
                    ps1.setString(1,b);
                    ps1.setString(2,c);
                    ps1.setString(3,d);
                    ps1.setString(4,e);
                    ps1.setString(5,f);
                    ps1.setString(6,g);
                    ps1.setString(7,h);                 
                    ps1.setString(8,j);
                    ps1.setString(9,k);
                    ps1.setString(10,l);
                    ps1.setString(11,i);
                    ps1.setString(12,a);
                    
                    
                    
                     ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Updated");
                    
                    jTextFielda.setText("");
                    jTextFieldb.setText("");
                    jTextFieldc.setText("");
                    jTextFieldd.setText("");
                    jTextFielde.setText("");
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                    jComboBox1.setSelectedItem(null);
                    //jComboBox2.setSelectedItem(null);
                   // jTextField1.setText("");
                   jRadioButton1.setSelected(false);
                    jRadioButton2.setSelected(false);
                    jTextFieldj.setText("");
                    jTextFieldk.setText("");
                    jTextFieldl.setText("");
                    InvoiceNo();
            
                  
            }
            }catch (SQLException ex) {
            Logger.getLogger(Sites.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldkActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            PreparedStatement ps= null;
            ResultSet rs= null;
            
            String query="SELECT * FROM project_manager WHERE Status='Exist' ";
            ps=databaseConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox1.addItem(rs.getString("PM_ID"));
                
              
           /*PreparedStatement ps2= null;
            ResultSet rs2= null;
            
            String query2="SELECT * FROM client ";
            ps=databaseConnection.con().prepareStatement(query2);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox2.addItem(rs.getString("Client_ID"));
                
              
            }*/
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextFieldaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldb.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldaKeyPressed

    private void jTextFieldbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldbKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldc.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldbKeyPressed

    private void jTextFieldcKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldcKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldd.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldcKeyPressed

    private void jTextFielddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFielddKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldd.requestFocus();
        }
         String ph=jTextFieldd.getText();
     
      int len=ph.length();
     char c= evt.getKeyChar();
   // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
        
     if(len<10){
  jTextFieldd.setEditable(true);
    }else{
    jTextFieldd.setEditable(false);
     

     }
    }
      else{
   //erase number 'backspace work'
     if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
      jTextFieldd.setEditable(true);
   }else{
          jTextFieldd.setEditable(false);
     }
      }
    }//GEN-LAST:event_jTextFielddKeyPressed

    private void jTextFieldjKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldjKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldk.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldjKeyPressed

    private void jTextFieldkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldkKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jTextFieldl.requestFocus();
        }
          String ph=jTextFieldk.getText();
     
      int len=ph.length();
     char c= evt.getKeyChar();
   // check the character
      if(evt.getKeyChar()>='0'&& evt.getKeyChar()<='9'){
        
     if(len<10){
  jTextFieldk.setEditable(true);
    }else{
    jTextFieldk.setEditable(false);
     

     }
    }
      else{
   //erase number 'backspace work'
     if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
      jTextFieldk.setEditable(true);
   }else{
          jTextFieldk.setEditable(false);
     }
      }
    }//GEN-LAST:event_jTextFieldkKeyPressed

    private void jTextFielddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddSite().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddSite.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextFielda;
    private javax.swing.JTextField jTextFieldb;
    private javax.swing.JTextField jTextFieldc;
    private javax.swing.JTextField jTextFieldd;
    private javax.swing.JTextField jTextFielde;
    private javax.swing.JTextField jTextFieldj;
    private javax.swing.JTextField jTextFieldk;
    private javax.swing.JTextField jTextFieldl;
    // End of variables declaration//GEN-END:variables
}
