
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.CMYKColor;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.DocumentException;
import java.text.ParseException;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lahiru
 */
public class BreakDowns extends javax.swing.JFrame {

    /**
     * Creates new form BreakDowns
     */
    public BreakDowns() {
        initComponents();
        DisplayTable();
    }

    public void DisplayTable() {

        try {
            String query = "SELECT * FROM `breakdowns`";
            PreparedStatement ps = null;
            ResultSet rs = null;

            ps = databaseConnection.con().prepareStatement(query);
            rs = ps.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {
            Logger.getLogger(MachineDetials.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextFielda = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextFieldb = new javax.swing.JTextField();
        jTextFieldc = new javax.swing.JTextField();
        jTextFieldd = new javax.swing.JTextField();
        jTextFielde = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 636));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(550, 110, 20, 480);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Take");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(760, 540, 73, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(870, 540, 63, 30);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 173, 238));
        jLabel6.setText("Breakdown ID :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(640, 150, 110, 50);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Breakdown Details");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 30, 170, 50);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(950, 20, 67, 30);

        jPanel2.add(jPanel6);
        jPanel6.setBounds(0, 0, 1050, 90);
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(770, 460, 240, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 173, 238));
        jLabel5.setText("Taken date :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(650, 460, 100, 30);
        jPanel2.add(jTextFielda);
        jTextFielda.setBounds(770, 170, 160, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(940, 170, 73, 30);
        jPanel2.add(jTextFieldb);
        jTextFieldb.setBounds(770, 230, 240, 30);
        jPanel2.add(jTextFieldc);
        jTextFieldc.setBounds(770, 280, 240, 30);

        jTextFieldd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldd);
        jTextFieldd.setBounds(770, 340, 240, 30);
        jPanel2.add(jTextFielde);
        jTextFielde.setBounds(770, 400, 240, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 173, 238));
        jLabel2.setText("VID/MID :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(650, 280, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 173, 238));
        jLabel3.setText("Site ID :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(650, 340, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 173, 238));
        jLabel4.setText("Reported by :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(650, 400, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 173, 238));
        jLabel1.setText("Date :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(650, 230, 80, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Breakdown ID", "Date", "VID/MID", "Site ID", "Reported by"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 520, 330);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFielddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String a= jTextFielda.getText();
            String query ="SELECT  * FROM `breakdowns`  WHERE `ID` = ? ";
            PreparedStatement ps=null;
            ResultSet rs=null;
            ps=databaseConnection.con().prepareStatement(query);
            ps.setString(1, a);
            rs=ps.executeQuery();
            if(rs.next()){
                
                jTextFieldb.setText(rs.getString("Date"));
                jTextFieldc.setText(rs.getString("VID"));
                jTextFieldd.setText(rs.getString("Site_ID"));
                jTextFielde.setText(rs.getString("EmID"));   
                String datevalue2=rs.getString("TakenOn");
                java.util.Date date2= new SimpleDateFormat("yyyy-MM-dd").parse(datevalue2);
                 jDateChooser1.setDate(date2);
            }
            else{
                JOptionPane.showMessageDialog(this, "Not Found!");
                jTextFielda.setText("");
            }
        } catch (SQLException ex) {
            
        } catch (ParseException ex) {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            String a=jTextFielda.getText();
            String b=jTextFieldb.getText();
            String c=jTextFieldc.getText();
            String d=jTextFieldd.getText();
            String e=jTextFielde.getText();
           // String f=String.valueOf(jComboBox1.getSelectedItem());
            SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                String g=sdf.format(jDateChooser1.getDate());
          
            

            if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || d.equals("")  ||g.equals("") ){
               JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
               
            } 
            else{  
                try {
                    String query= "UPDATE `breakdowns` SET `TakenOn`=? WHERE  `ID`=?";
                    PreparedStatement ps1=null;
                    
                    ps1=databaseConnection.con().prepareStatement(query);
                    
                   // ps1.setString(1,f);
                    ps1.setString(1,g);
                    ps1.setString(2,a);
                    
                    
                    
                    ps1.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Taken!");
                    
                    jTextFielda.setText("");
                    jTextFieldb.setText("");
                    jTextFieldc.setText("");
                    jTextFieldd.setText("");
                    jTextFielde.setText("");
                    //jComboBox1.setSelectedItem(null);
                    jDateChooser1.setDate(null);
                    DisplayTable();;
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
                   
            }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                    jTextFielda.setText("");
                    jTextFieldb.setText("");
                    jTextFieldc.setText("");
                    jTextFieldd.setText("");
                    jTextFielde.setText("");
                    //jComboBox1.setSelectedItem("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
       // Workshop a= new Workshop();
        //a.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//      try {
//            PreparedStatement ps= null;
//            ResultSet rs= null;
//            
//            String query="SELECT * FROM workshop ";
//            ps=databaseConnection.con().prepareStatement(query);
//            rs=ps.executeQuery();
//            while(rs.next()){
//                jComboBox1.addItem(rs.getString("WID"));   
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
//        } 
      
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BreakDowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BreakDowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BreakDowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BreakDowns.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BreakDowns().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFielda;
    private javax.swing.JTextField jTextFieldb;
    private javax.swing.JTextField jTextFieldc;
    private javax.swing.JTextField jTextFieldd;
    private javax.swing.JTextField jTextFielde;
    // End of variables declaration//GEN-END:variables
}
