
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class Hirings extends javax.swing.JFrame {

    /**
     * Creates new form Hirings
     */
    public Hirings() throws SQLException {
        initComponents();
        InvoiceNo();
    }
    
     public void InvoiceNo() throws SQLException{
        String query = "SELECT MAX(ID)FROM hiring2 ";
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = databaseConnection.con().prepareStatement(query);
            rs = ps.executeQuery();
            if(rs.next()){
            rs.getString("MAX(ID)");
            
            if(rs.getString("MAX(ID)")==null){
                jTextField1.setText("H001");
            }else{
               
                
                String id=String.valueOf(rs.getString("MAX(ID)"));
             
                String id1=id.substring(0,1);
                String id2=id.substring(2,4);
               long n= Long.parseLong(id2);
                n++;
                String num1=Long.toString(n);
                jTextField1.setText(id1+String.format("%03d",n));
            }
            }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(436, 630));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setMinimumSize(new java.awt.Dimension(436, 80));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HIRINGS");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 10, 130, 50);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(950, 30, 67, 30);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4);
        jButton4.setBounds(360, 20, 60, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 440, 80);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setText("Hiring ID :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 70, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Hired by :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 170, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 255));
        jLabel5.setText("Hired From :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 220, 80, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("Hired Date :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 270, 80, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Return Date :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 320, 80, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("ADD");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(100, 410, 70, 30);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("UPDATE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(180, 410, 80, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 410, 80, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 120, 230, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(130, 220, 230, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(130, 270, 230, 30);
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(130, 320, 230, 30);

        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(130, 170, 130, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 70, 150, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("Type & Capcity");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 90, 15);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Search");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(290, 70, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 440, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.dispose();
        AdminHiring a = new AdminHiring();
        a.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        PreparedStatement ps=null;
        ResultSet rs1=null;
        ResultSet rs2=null;

        String a=jTextField1.getText();
       // String b=String.valueOf(jComboBox3.getSelectedItem());
        String b=jTextField2.getText();
        String c=String.valueOf(jComboBox2.getSelectedItem());
        String d=jTextField4.getText();
      
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                String e=sdf.format(jDateChooser1.getDate());
                String f=sdf.format(jDateChooser2.getDate());
        

        if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || e.equals("") || f.equals("")){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields !");

        } else{
            try {
                String query_A="SELECT * FROM `hiring2` WHERE ID=? ";
                ps=databaseConnection.con().prepareStatement(query_A);
                ps.setString(1, a);
                rs1=ps.executeQuery();

                if(rs1.next()){
                    JOptionPane.showMessageDialog(this,"Invalid ID");
                }
                else{
                    String query= "INSERT INTO `hiring2`"
                    +"(`ID`, `TypeCapcity`,`HiredBy`, `HiredDate`, `ReturnDate`, `HiredFrom`)"
                    +"VALUES (?,?,?,?,?,?)";
                    ps=databaseConnection.con().prepareStatement(query);

                    ps.setString(1,a);
                    ps.setString(2,b);
                    ps.setString(3,c);
                    ps.setString(4,e);
                    ps.setString(5,f);
                    ps.setString(6,d);
                  

                    ps.execute();

                    JOptionPane.showMessageDialog(this, "Done!");
                    
                    jTextField2.setText("");
                    jComboBox2.setSelectedItem(null);
                    jTextField4.setText("");
                   // jComboBox3.setSelectedItem(null);
                    jTextField1.setText("");
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                    InvoiceNo();

                }
            } catch (SQLException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String a=jTextField1.getText();
       // String b=String.valueOf(jComboBox3.getSelectedItem());
        String b=jTextField2.getText();
        String c=String.valueOf(jComboBox2.getSelectedItem());
        String d=jTextField4.getText();
      
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
                String e=sdf.format(jDateChooser1.getDate());
                String f=sdf.format(jDateChooser2.getDate());
        

        if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || e.equals("") || f.equals("")){
            JOptionPane.showMessageDialog(this, "Please Fill all Fields !");

        }
        else{
            try {
                String query= "UPDATE `hiring2` SET `TypeCapcity`=?, `HiredBy`=?, `HiredDate`=?, `ReturnDate`=?, `HiredFrom`=? WHERE  `ID`=?";
                PreparedStatement ps1=null;

                ps1=databaseConnection.con().prepareStatement(query);

                ps1.setString(1,b);
                ps1.setString(2,c);
                ps1.setString(3,e);
                ps1.setString(4,f);
                ps1.setString(5,d);
                ps1.setString(6,a);
                

                ps1.executeUpdate();
                JOptionPane.showMessageDialog(this,"Updated");

                   
                    jTextField2.setText("");
                    jComboBox2.setSelectedItem("");
                    jTextField4.setText("");
                   // jComboBox3.setSelectedItem("");
                   jTextField1.setText("");
                    jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
                    InvoiceNo();

            } catch (SQLException ex) {
                Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   
                    jTextField2.setText("");
                    jComboBox2.setSelectedItem(null);
                    jTextField4.setText("");
                    //jComboBox3.setSelectedItem(null);
                    jTextField1.setText("");
                     jDateChooser1.setDate(null);
                    jDateChooser2.setDate(null);
        try {
            InvoiceNo();
        } catch (SQLException ex) {
            Logger.getLogger(Hirings.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            PreparedStatement ps= null;
            ResultSet rs= null;
            
            String query="SELECT * FROM site WHERE Status='Not completed' ";
            ps=databaseConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox2.addItem(rs.getString("Site_ID"));
             }   
                
                
            PreparedStatement ps2= null;
            ResultSet rs2= null;
            
            String query2="SELECT * FROM vehicles_and_machines ";
            ps=databaseConnection.con().prepareStatement(query2);
            rs=ps.executeQuery();
            while(rs.next()){
               // jComboBox3.addItem(rs.getString("ID"));
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ResultSet rs=null;
        try {
            String a= jTextField1.getText();
            String query ="SELECT  * FROM `hiring2`  WHERE ID = ? ";
            PreparedStatement ps=null;
            ps=databaseConnection.con().prepareStatement(query);
            ps.setString(1, a);
            rs=ps.executeQuery();
            if(rs.next()){

                jTextField2.setText(rs.getString("TypeCapcity"));
                jTextField4.setText(rs.getString("HiredFrom"));
                String datevalue=rs.getString("HiredDate");
                String datevalue2=rs.getString("ReturnDate");
               // String hiredy=rs.getString("HiredBy");
                // jTextField1.setText(rs.getString("Project_Manager"));
                
                    java.util.Date date= new SimpleDateFormat("yyyy-MM-dd").parse(datevalue);
                    java.util.Date date2= new SimpleDateFormat("yyyy-MM-dd").parse(datevalue2);
                    jDateChooser1.setDate(date);
                    jDateChooser2.setDate(date2);
                

                jComboBox2.setSelectedItem(rs.getString("HiredBy"));
               
               
            
            }else{
                JOptionPane.showMessageDialog(this, "Not Found!");
                jTextField1.setText("");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Sites.class.getName()).log(Level.SEVERE, null, ex);

        } catch (ParseException ex) {
            Logger.getLogger(Hirings.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hirings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hirings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hirings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hirings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Hirings().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Hirings.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
