
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lahiru
 */
public class ReportBreakdown extends javax.swing.JFrame {

    /**
     * Creates new form ReportBreakdown
     */
    public ReportBreakdown() throws SQLException {
        initComponents();
        InvoiceNo();
    }
    public void InvoiceNo() throws SQLException{
        String query = "SELECT MAX(ID)FROM breakdowns ";
            PreparedStatement ps = null;
            ResultSet rs = null;
            ps = databaseConnection.con().prepareStatement(query);
            rs = ps.executeQuery();
            if(rs.next()){
            rs.getString("MAX(ID)");
            
            if(rs.getString("MAX(ID)")==null){
                jTextField1.setText("B001");
            }else{
               
                
                String id=String.valueOf(rs.getString("MAX(ID)"));
             
                String id1=id.substring(0,1);
                String id2=id.substring(2,4);
               long n= Long.parseLong(id2);
                n++;
                String num1=Long.toString(n);
                jTextField1.setText(id1+String.format("%03d",n));
            }
            }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(454, 485));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setMinimumSize(new java.awt.Dimension(504, 80));
        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Report a Breakdown");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 10, 220, 50);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1);
        jButton1.setBounds(370, 30, 60, 23);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 450, 80);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 400, 100, 40);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 400, 100, 40);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(null);

        jComboBox1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jComboBox1ComponentAdded(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBox1FocusLost(evt);
            }
        });
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jComboBox1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBox1MouseReleased(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(210, 90, 130, 30);

        jPanel1.add(jComboBox3);
        jComboBox3.setBounds(210, 190, 130, 30);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(210, 240, 190, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 173, 238));
        jLabel3.setText("BreakDown ID:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 40, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 173, 238));
        jLabel9.setText("Breakdown date:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 240, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 173, 238));
        jLabel6.setText("Engineer ID :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 190, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 173, 238));
        jLabel4.setText("Site Id:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 140, 140, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 173, 238));
        jLabel5.setText("Vehicle/Machine ID:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 90, 150, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(210, 40, 130, 30);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(210, 140, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 80, 450, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         jComboBox1.setSelectedItem(null);
                jTextField2.setText(null);
                jComboBox3.setSelectedItem(null);
                jDateChooser1.setDate(null);
                 jTextField1.setText("");
               
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        PreparedStatement ps=null;
        ResultSet rs1=null;
        String a=String.valueOf(jComboBox1.getSelectedItem());
        String b=jTextField2.getText();
        String c=String.valueOf(jComboBox3.getSelectedItem());
        SimpleDateFormat sdf= new SimpleDateFormat("yyyy-MM-dd");
        String d=sdf.format(jDateChooser1.getDate());
        String e=jTextField1.getText();
       if(a.equals("") || b.equals("") || c.equals("") || d.equals("") || e.equals("") ){
               JOptionPane.showMessageDialog(this, "Please Fill all Fields !");
               
            }else{
            
            try {
                String query= "INSERT INTO `breakdowns`"
                        +"(`ID`,`Date`, `VID`, `Site_ID`,`EmID`)"
                        +"VALUES (?,?,?,?,?)";
                ps=databaseConnection.con().prepareStatement(query);
                ps.setString(1,e);
                ps.setString(2,d);
                ps.setString(3,a);
                ps.setString(4,b);
                ps.setString(5,c);
                
                ps.execute();
                JOptionPane.showMessageDialog(this, "Reported!");
                
                jComboBox1.setSelectedItem(null);
                jTextField2.setText(null);
                jComboBox3.setSelectedItem(null);
                jDateChooser1.setDate(null);
                jTextField1.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(ReportBreakdown.class.getName()).log(Level.SEVERE, null, ex);
            }
               
            
            
            
        }
        
            
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        BrakeDownsE b= new BrakeDownsE();
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try {
            PreparedStatement ps= null;
            ResultSet rs= null;
            
            String query="SELECT * FROM vehicles_and_machines ";
            ps=databaseConnection.con().prepareStatement(query);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox1.addItem(rs.getString("ID"));  
            }
            PreparedStatement ps2= null;
            ResultSet rs2= null;
            
//            String query2="SELECT * FROM site";
//            ps=databaseConnection.con().prepareStatement(query2);
//            rs=ps.executeQuery();
//            while(rs.next()){
//                jComboBox2.addItem(rs.getString("Site_ID"));
//            }
            
            PreparedStatement ps3= null;
            ResultSet rs3= null;
            
            String query3="SELECT * FROM employee";
            ps=databaseConnection.con().prepareStatement(query3);
            rs=ps.executeQuery();
            while(rs.next()){
                jComboBox3.addItem(rs.getString("EmID"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
       
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseReleased
       
    }//GEN-LAST:event_jComboBox1MouseReleased

    private void jComboBox1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseExited
       
    }//GEN-LAST:event_jComboBox1MouseExited

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jComboBox1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jComboBox1ComponentAdded
        
    }//GEN-LAST:event_jComboBox1ComponentAdded

    private void jComboBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MousePressed
        
    }//GEN-LAST:event_jComboBox1MousePressed

    private void jComboBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusLost
        
    }//GEN-LAST:event_jComboBox1FocusLost

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        try {
            PreparedStatement ps= null;
            ResultSet rs= null;
            String a= String.valueOf(jComboBox1.getSelectedItem());
            String sql="SELECT Site_ID FROM vehicles_and_machines WHERE ID=?";
            ps=databaseConnection.con().prepareStatement(sql);
            ps.setString(1,a);
            rs=ps.executeQuery();
            if(rs.next()){
                jTextField2.setText(rs.getString("Site_ID"));
            }} catch (SQLException ex) {
            Logger.getLogger(ReportBreakdown.class.getName()).log(Level.SEVERE, null, ex);
        }
             
    }//GEN-LAST:event_jTextField2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportBreakdown.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ReportBreakdown().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ReportBreakdown.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
